### ISSUE TITLE
[Update] : README.md file 

### ISSUE THREAD

**Issue by Rahul-Prasad-07** [spacelift-io/spacectl#127]
Make README.md file more interactive and attractive

**Comment by peterdeme** [comment]
Hello @Rahul-Prasad-07 - is there any particular thing you think of?

**Comment by tomasmik** [comment]
We've updated the file slightly and seeing how this is stale, I'm closing it.

https://github.com/spacelift-io/spacectl/commit/4e8ad8414764ab7851bda230f02b5a21ccaed340
