### ISSUE TITLE
Feature request: Add spacectl to Chocolatey

### ISSUE THREAD

**Issue by TechnicallyJoe** [spacelift-io/spacectl#151]
Chocolatey is a windows package manager https://chocolatey.org/
Alternatively (or also) winget https://learn.microsoft.com/en-us/windows/package-manager/package/

Thanks!

**Comment by peterdeme** [comment]
@TechnicallyJoe is the winget installation issue solved now?

**Comment by peterdeme** [comment]
CC @mbialon
