### ISSUE TITLE
Error (and crash) when using web browser login flow inside devcontainer

### ISSUE THREAD

**Issue by lohrm-stabl** [spacelift-io/spacectl#152]
I get the following error when using spacectl (spacectl version 0.22.0, 0.23.0 and 0.24.0) from a vscode [devcontainer](https://containers.dev/):

```
Enter Spacelift endpoint (eg. https://unicorn.app.spacelift.io/): https://********.app.spacelift.io
Select authentication flow: 
  1) for API key,
  2) for GitHub access token,
  3) for login with a web browser
Option: 3
Waiting for login responses at 127.0.0.1:45557

Opening browser to https://*******

2023/06/15 14:11:13 exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH
```
After this the program exits with a negative exit code.

However, the `aws sso login` command which uses a similar flow works without problems - so its possible to automatically open a browser and ask for authentication.

Additionally, one could just click the link manually if spacectl wouldn't crash.

**Comment by lohrm-stabl** [comment]
`kubectl` will actually produce the same error (https://www.dbi-services.com/blog/kubernetes-sso-using-azure-ad/), but instead of crashing it, it waits until the link was clicked manually.

**Comment by lohrm-stabl** [comment]
This is a showstopper for us since we basically cannot use `spacectl` without paying twice for every user because we have to set up an API key for every user (and pay for the API key as well as the user, even both the web interface and spacectl are used by the same user).

**Comment by tomasmik** [comment]
It should be possible to change how the login with the browser works to not crash when we fail to open a browser window. I will investigate and make changes.

**Comment by tomasmik** [comment]
I believe this issue is fixed in release: https://github.com/spacelift-io/spacectl/releases/tag/v0.24.1
