### ISSUE TITLE
Set the tracked commit by tag

### ISSUE THREAD

**Issue by DDSpacelift** [spacelift-io/spacectl#154]
Customer said:
It's possible to set the tracked commit of a stack using `spacectl stack set-current-commit --id --sha `

I would like to set the tracked commit by tag instead. Something like `spacectl stack set-current-commit --id --tag 0.1.2`

This would be very useful for us, as all commits that are proposed/tracked are tagged and a tag is much easier to understand than a raw commit sha.
---
We're using git commands to do this SHA/tag mapping already, but it would
make our workflow much simpler if this could be wrapped up inside the
spacectl command

**Comment by tomasmik** [comment]
Unfortunately this is not supported by the API so adding something like that is not trivial.

**Comment by tomasmik** [comment]
Done!

**Comment by tomasmik** [comment]
the --sha param now supports refs for github and gitlab.

```
spacectl stack set-current-commit --id stacks --sha refs/tags/v1.2.0
Current commit set to "Update config.yml": (SHA 339ef5401f08ac7f35ba692f3.....)
```
