### ISSUE TITLE
Command args for `login` command

### ISSUE THREAD

**Issue by lohrm-stabl** [spacelift-io/spacectl#158]
We used `spacectl` in short-lived development containers. This is way we have to execute `spacectl profile login` very often.
It would be great if we could supply the URL and authentication kind via command args. Its quite tedious to use the interactive interface to always type the URL and select the authentication method manually.

I imagine something like this:
```bash
spacectl profile login --url https://myaccount.app.spacelift.io --method browser
```

**Comment by varshneydevansh** [comment]
I am excited to contribute to this project, are there any issue which are a little beginner-friendly or any new feature implementation?

**Comment by tomasmik** [comment]
> I am excited to contribute to this project, are there any issue which are a little beginner-friendly or any new feature implementation?

Hi! Sorry for the late reply, sadly contributing without having a spacelift account is not that simple as most features require at least a free version of spacelift while some require a paid one. Issues also aren't sorted and tagged or lack proper description for easy first time contributing.
