### ISSUE TITLE
Extract Spacelift API client as a standalone library

### ISSUE THREAD

**Issue by alexjurkiewicz** [spacelift-io/spacectl#189]
So I can use it for my own experiments. Please? 🙏

**Comment by tomasmik** [comment]
I believe that the client itself is pretty much all you need and it's already a separate package: https://github.com/spacelift-io/spacectl/blob/main/client/client.go

We do not have any premade API requests, they are mostly [crafted where they are used](https://github.com/spacelift-io/spacectl/blob/main/internal/cmd/stack/resources.go#L30) with no generic client.

**Comment by peterdeme** [comment]
To add to Tomas' comment, probably there are also better ways to do it. Like some sort of code generator like [this](https://the-guild.dev/graphql/codegen) one.

**Comment by alexjurkiewicz** [comment]
Thank you for the feedback! The client has been great 😸
