### ISSUE TITLE
Feature request: `spacectl browse` to open current stack in browser

### ISSUE THREAD

**Issue by alexjurkiewicz** [spacelift-io/spacectl#191]
I use [hub](https://hub.github.com/) a lot, and a favourite feature is `git browse`, to open the current repo in my web browser.
I'd like a similar feature for `spacectl`. Running `spacectl browse` should open the current stack in a web browser.

It can identify the current stack by:
1. Repository name matches
2. If required, project root matches (eg for monorepos)
3. If there are still many matching stacks, either open the browser to show all matching stacks in a filtered stack listing, or ask the user in a web terminal to select one

**Comment by tomasmik** [comment]
Doesn't `spacectl stack open` already do that?

```
➜  spacectl stack open --help
NAME:
   spacectl stack open - Open a stack in your browser

USAGE:
   spacectl stack open [command options] COMMAND

CATEGORY:
   Stack management

OPTIONS:
   --ignore-subdir   [Optional] Indicate whetever open command should ignore the current subdir and only use the repository to search for a stack (default: false)
   --current-branch  [Optional] Indicate whetever to search a stack by the current branch you're on (default: false)
   --count value     [Optional] Indicate the maximum count of elements returned when searching stacks (default: 30)
   ```

**Comment by tomasmik** [comment]
Also `--id` parameter in all stack commands is optional and can be inferred by the same logic

```
   --id ID               [Optional] User-facing ID (slug) of the stack, if not provided stack search is used lookup the stack ID by the current directory and repository name
```

**Comment by alexjurkiewicz** [comment]
Wow, I totally missed that, thanks! 😱
