### ISSUE TITLE
Add ability to delete stacks

### ISSUE THREAD

**Issue by jwenz723** [spacelift-io/spacectl#195]
It would be nice if the spacectl cli offered a command to delete stacks. Something like `spacectl stack delete --id my-stack-id`.

I typically manage the creation/deletion of stacks using terraform. However, in my automated testing of my module which is used for stack provisioning I occasionally need to delete stacks manually which were created during automated testing due to failures that occur during a test. Today I have to go into the spacelift UI and manually click the `delete` button. It would be nice to be able to script this so that if my automated test fails then it can try to perform cli commands to clean up the failed stacks.

**Comment by tomasmik** [comment]
Spacectl isn't really made for creating, mutating or deleting resources such as stacks. While I understand the reasoning behind this request, I'm not sure if we'll implement this.

**Comment by peterdeme** [comment]
Perhaps a workaround for your problem would be adding a [scheduled delete](https://docs.spacelift.io/concepts/stack/scheduling.html#scheduled-delete-stack-ttl) to your stack.

**Comment by tomasmik** [comment]
I feel like Peters suggestion there is sufficient and we will not implement any stack mutation in spacectl for now.
