### ISSUE TITLE
Feature request: show current tracked commit for a stack

### ISSUE THREAD

**Issue by Nuru** [spacelift-io/spacectl#20]
I would like to have a command like
```
spacectl stack get-current-commit <stack-id-slug>
```
that returns the current tracked commit for the given stack. One obvious use case is so that I can verity that `set-current-commit` has taken effect.

**Comment by adamconnelly** [comment]
@Nuru sorry for the delayed response. I've been trying to have a think about the full set of commands that we should support with `spacectl` to try to ensure we end up with a consistent interface. I've written up my thoughts here: https://github.com/spacelift-io/spacectl/blob/main/specs/spacectl-to-v1.md#commands.

I'm just wondering, would a `spacectl stack show` command that output the current tracked commit along with other information about the stack work for you. So something like this:

```shell
$ spacectl stack show --id test-stack
{
  "id": "test-stack",
  "trackedCommit": {
    "hash": "b605cdfe15a2d87d73218118737972fbcec3335d",
    "message": "Made some changes"
  },
  ...
}
```

That way you can get the tracked commit, but you can also get other info about the stack that you might need, so we don't need to add separate commands for each piece of info you might want.

Let me know what you think.

**Comment by Nuru** [comment]
@adamconnelly I understand the difficulty of developing a command-line interface, and I realize that there between getting things quickly and getting things exactly how I want them.

In the long run, I like to have commands that output human-oriented text that is also suitable for `bash` scripting. Convenience and ease of use usually end up meaning lots of commands and options.

In the short run, having some way to get things done is preferable to having no way to get them done, so whatever is your shortest development path will be a good place to start. JSON output with lots of information from one or a few commands works for me for the short term. 

Consider a recent use case we were not able to accomplish: find all failed stacks and retry the failed commits. I would rather be able to do that with the CLI and `jq` and maybe even some manual intervention than have to click through the WebUI hundreds of times.

**Comment by adamconnelly** [comment]
@Nuru you can now view the current tracked commit for a stack using the `stack list` command. We'll add a `stack show` command soon, but the info is included in the `stack list` output:

```shell
> spacectl stack list
Name                          | Commit   | Author        | State     | Worker Pool | Locked By
stack-1                       | 1aa0ef62 | Adam Connelly | NONE      |             |
stack-2                       | 1aa0ef62 | Adam Connelly | DISCARDED |             |
```

You can also use `stack list` for your scenario of automatically retrying all failed stacks. We'll probably add filtering to the command, but for now you can use `jq`:

```shell
$ spacectl stack list --output json | jq -r '.[] | select(.state | contains("FAILED")) | .id' | xargs -l1 spacectl stack deploy --id
You have successfully created a deployment
The live run can be visited at http://adamconnelly.app.spacelift.tf/stack/azure-stack/run/01FAQH7B95ZMMDZSWBS3BRRMZ1
You have successfully created a deployment
The live run can be visited at http://adamconnelly.app.spacelift.tf/stack/infracost-aws/run/01FAQH7BM6FKMN19B24EK8AVYX
```

**Comment by adamconnelly** [comment]
I'm going to close this for now since you can achieve this using the `stack show` command:

```
spacectl stack show --id simple-stack -o json | jq -r '.trackedCommit.hash'
```

Once we've got more functionality in place we can think about whether it makes sense to add more specific commands.
