### ISSUE TITLE
Unable to pass CLI_ARGS to a stack using --tf-env-var-override or --env-var-override 

### ISSUE THREAD

**Issue by kennyhutcheson** [spacelift-io/spacectl#206]
Currently I'm unable to pass a different TF_CLI_ARGS=-var-file=mytfvars/dev.tfvars using local preview. 

This appears to be because the string is using the = as the split of the passed argument where the CLI_ARGS can have this included so it's not a valid option to use. 

Running command

```
spacectl stack local-preview --id <STACKID>  --env-var-override 'TF_CLI_ARGS=-var-file=mytfvars/dev.tfvars'
```

Outcome 

```
2023/12/11 11:54:22 invalid environment variable "CLI_ARGS=-var-file=damint/dev.tfvars", must be in the form of KEY=VALUE
```

https://github.com/spacelift-io/spacectl/blob/44d279be302ca318ee0f141410186ca8419073e2/internal/cmd/stack/local_preview.go#L151

**Comment by tomasmik** [comment]
Should be fixed by: https://github.com/spacelift-io/spacectl/pull/208 and will be included in the next release.
