### ISSUE TITLE
local-preview cannot create run

### ISSUE THREAD

**Issue by wjbabicz** [spacelift-io/spacectl#224]
`> spacectl -v
spacectl version 0.30.0`

Getting this error when trying to execute a local-preview:

`> spacectl stack local-preview --id github-private
Packing local workspace...
Uploading local workspace...
126.48 KiB / 126.48 KiB [-----------------------------------------------------------------------------------------] 100.00% 271.54 KiB p/s 700ms
2024/04/09 15:50:15 could not create run: could not persist run: commit author name must not be empty`

I can confirm the author name is set globally in my git config, not sure if there are any configuration steps I'm missing. Can execute other commands in the spacectl (list stacks, etc), so I'm definitely logged in and the token is valid.

**Comment by marcinwyszynski** [comment]
We are aware of this regression. It covers users for whom the IdP connected to Spacelift does not return a full name (or else, returns an empty string). This is not a `spacectl` issue per se, this is an overly strict backend validation. Please stay tuned for the fix, and apologies for the inconvenience caused.

**Comment by wjbabicz** [comment]
No worries -- appreciate the response! 😄

**Comment by TheMacies** [comment]
@wjbabicz We've addressed the regression on the backend side. Please check if the issue has been resolved.

**Comment by wjbabicz** [comment]
@TheMacies Looking good! TYVM
