### ISSUE TITLE
Find Stack given Run ID

### ISSUE THREAD

**Issue by Nuru** [spacelift-io/spacectl#230]
In many places, particularly logging output captured by Datadog, I have access to a Run ID, but not the stack name. In general (maybe in all cases), `spacectl` and the web UI can do nothing with a Run ID unless you also supply the stack ID/slug.

Please add a way to get the Stack ID associated with a Run ID.

**Comment by tomasmik** [comment]
While in theory this is possible, it's not as simple as just adding it to spacectl because backend doesn't provide a way to resolve a run (and to which stack it belongs) by just providing a run ID. To complete this, we would first need to extend backend.
