### ISSUE TITLE
Feature request: `spacectl module delete-version`

### ISSUE THREAD

**Issue by nessex** [spacelift-io/spacectl#254]
Hi 👋 would it be possible to get a `spacectl module delete-version` command added to spacectl?

I'm currently setting up a workflow for our modules that involves automatically creating many versions. However, these versions are only useful for a short time. Given each version will sit around in the UI, and each will involve an archive getting created and pushed to e.g. S3, I'd really like to be able to clean up. The UI offers up a way to delete versions, but deleting them manually will be impractical in this case and I'd like to automate it. Having a command in the CLI would make this much easier!

**Comment by tomasmik** [comment]
This is tricky, spacectl isn't meant for create or delete operations, but in this case maybe it makes sense.

**Comment by nessex** [comment]
Thanks! I think there is a path we could take with the GraphQL API to self-serve on this regardless, but I figured it'd kind of fit alongside `spacectl module create-version`.

**Comment by tomasmik** [comment]
@nessex your feature will be included in the next release, thanks for submitting a request :)

**Comment by nessex** [comment]
Thanks so much!
