### ISSUE TITLE
Add Create commands for spaces

### ISSUE THREAD

**Issue by kotowick** [spacelift-io/spacectl#261]
We could like to automate creating spaces on the fly with `spacectl`.

**Why?**
_The only current options are:_
- mono repo defining all spaces with one admin stack
- having an admin stack per github application repo which would create a space per region/environment deplyoment
- creating manually

**Comment by tomasmik** [comment]
This is not gonna be implemented. Please use the [terraform provider](https://github.com/spacelift-io/terraform-provider-spacelift)

spacectl support as little creation and deletion as possible on purpose. We do not want this to become a tool to replace the terraform provider.
