### ISSUE TITLE
Add Create commands for stacks

### ISSUE THREAD

**Issue by kotowick** [spacelift-io/spacectl#262]
We could like to automate creating stacks on the fly with spacectl.

**Why?**
_The only current options are:_
- mono repo defining all spaces with one admin stack
- having an admin stack per github application repo which would create a space per region/environment deplyoment
- creating manually

**Comment by tomasmik** [comment]
This is not gonna be implemented. Please use the [terraform provider](https://github.com/spacelift-io/terraform-provider-spacelift)
