### ISSUE TITLE
Add `--no-color` option for table output

### ISSUE THREAD

**Issue by adamconnelly** [spacelift-io/spacectl#52]
Add a `--no-color` option that stops us from outputting ANSI escape codes in the table output. At the moment this makes it difficult for people to parse the table output. A better option is to use the JSON output format for parsing, but there's no harm in removing the escape codes.

**Comment by srhopkins** [comment]
I'm more interested in the `JSON` output option, not sure if that should be a separate feature request as this thread seems to mainly focus on the `--no-color` flag

**Comment by adamconnelly** [comment]
@srhopkins apologies for the late response - just noticed this comment. We already support JSON output via the `-o|--output` option. For example:

```shell
spacectl stack list -o json
```
