### ISSUE TITLE
Add a `spacectl stack retry` command

### ISSUE THREAD

**Issue by adamconnelly** [spacelift-io/spacectl#53]
Add a new command that allows runs to be retried:

```shell
spacectl stack retry --stack-id my-stack --run-id 01FZFGJAQWJ6J1QCMDB5TEDJ5J
```

**Comment by cbisnett** [comment]
This is a command I've used to retry the last failed run of a stack.
`spacectl stack retry --tail --id aws-infrastructure --run `spacectl stack run list --id aws-infrastructure -o json --max-results 1 | jq -r '.[0].id'``

**Comment by tomasmik** [comment]
This exists
