### ISSUE TITLE
Implement spacectl open

### ISSUE THREAD

**Issue by marcinwyszynski** [spacelift-io/spacectl#54]
Feature request: `spacectl open` -- when run inside a git repo, open the corresponding Spacelift stack in my browser.
(Bonus #1: if there are multiple matching stacks, show a menu/selector)
(Bonus #2: remember my choice based on git repo and subdir within (for monorepos), so I only have to select once)

**Comment by tomasmik** [comment]
Done in: https://github.com/spacelift-io/spacectl/pull/117
