### ISSUE TITLE
Homebrew install fails with draft releases

### ISSUE THREAD

**Issue by adamconnelly** [spacelift-io/spacectl#63]
At the moment our release process for spacectl is as follows:

- Create a tag for the new version (e.g. `v0.9.2`).
- This triggers the [release workflow](https://github.com/spacelift-io/spacectl/blob/main/.github/workflows/release.yml), which runs goreleaser, doing the following:
  - Builds and signs the code.
  - Creates a GitHub draft release.
  - Publishes the new version to Homebrew.
- We then edit the release notes, and publish the draft release.

The problem with this is that Homebrew then points at the draft release, which causes downloads to fail. Here's an example of the error:

```shell
$ brew install spacelift-io/spacelift/spacectl
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

==> Downloading https://github.com/spacelift-io/spacectl/releases/download/v0.9.2/spacectl_0.9.2_darwin_arm64.zip
curl: (22) The requested URL returned error: 404

Error: spacectl: Failed to download resource "spacectl"
Download failed: https://github.com/spacelift-io/spacectl/releases/download/v0.9.2/spacectl_0.9.2_darwin_arm64.zip
```

**Comment by adamconnelly** [comment]
Here's a couple of options that come to mind:

- Prevent goreleaser from creating a draft release. In this case maybe we could manually create the draft release, and goreleaser would publish it.
- Maybe we can split the goreleaser workflow into two stages:
  - Building the code and publishing the initial draft release.
  - Publishing to Homebrew when the release is published.

@jmfontaine any thoughts on this since you added the Homebrew support?

**Comment by cube2222** [comment]
Maybe we could have .goreleaser make the relevant changes to the Homebrew repo on a branch, instead of on main, so that we can manually merge it once we confirm the release on this repo.

**Comment by jmfontaine** [comment]
@adamconnelly @cube2222 I did not realize that we create draft releases. Why is that?

I honestly do not see the point of creating draft releases but I might be missing something. 😄

**Comment by adamconnelly** [comment]
I suspect it was to give us the chance to edit the release notes or do some testing before publishing, but maybe @marcinwyszynski knows for sure?

Assuming there's no objections, I think we should go with the simple option of not creating draft releases, and if we need the ability to tweak the release notes before publishing we can come up with another option (e.g. just creating a file in the repo).

**Comment by adamconnelly** [comment]
I've disabled draft releases in goreleaser. I don't want to create a new release just to test this change, so we can wait until the next release to try it out.
