### ISSUE TITLE
First time login with an empty endpoint creates an invalid URL

### ISSUE THREAD

**Issue by lexton** [spacelift-io/spacectl#89]
Hey there, I’m trying to get spacelift working locally, but having problems getting logged in.  When I try to authenticate I immediately get an error and no browser window opens:

```
$ spacectl profile <name> login 
Enter Spacelift endpoint (eg. https://unicorn.app.spacelift.io/): 
Select authentication flow: 
  1) for API key,
  2) for GitHub access token,
  3) for login with a web browser
Option: 3

Opening browser to /cli_login?key=<REDACTED>

2022/09/09 12:07:10 could not wait for the opening browser: exit status 1
```

It's an annoying problem - but its the first use of the spacectl that causes a bit of a weird problem since folks are just getting started.

The workaround is to actually specify the endpoint you want to use - but the error messaging doesn't really reflect this.

**Comment by jmfontaine** [comment]
Thanks for the bug report @lexton!

We should probably exit with an error if no endpoint is provided instead of moving on only to fail with a confusing error message.

**Comment by b4k3r** [comment]
@lexton, thanks for raising the issue. We've already provided the fix, and it should be released soon.
