### ISSUE TITLE
Add ability to show logs from the latest run with `spacectl stack logs --id <stack-name>`

### ISSUE THREAD

**Issue by tbublik** [spacelift-io/spacectl#93]
Hi, right now one can use `spacectl` to output logs of a specific stack run, but it would be amazing if running `spacectl stack logs --id <stack-id>` would just show logs of the latest run, because it's quite inconvenient to first run `spacectl stack run list --id <stack-name>` to get a run id while in the wast majority of cases all I need is the latest run.

**Comment by tomasmik** [comment]
This is now possible: https://github.com/spacelift-io/spacectl/pull/171
